"""
Driver Performance Analytics page.
Displays active drivers count, vehicle metrics, rating distributions, and top high-earner drivers.
"""
import streamlit as st
import pandas as pd
from dashboard.utils.db import run_query, format_rupiah, format_number
from database.olap_queries import (
    q_driver_performance_summary,
    q_driver_rating_distribution,
    q_top_drivers,
)
from dashboard.components.charts import bar_grouped, gauge_kpi
from dashboard.components.kpi_cards import section_header, insight_box


def render(filters: dict):
    # Fetch data based on dynamic sidebar filters
    df_summary = run_query(q_driver_performance_summary(
        years=filters.get("years"), regions=filters.get("regions"), services=filters.get("services")
    ))
    df_rating  = run_query(q_driver_rating_distribution(
        years=filters.get("years"), regions=filters.get("regions"), services=filters.get("services")
    ))
    df_top     = run_query(q_top_drivers(
        limit=150, years=filters.get("years"), regions=filters.get("regions"), services=filters.get("services")
    ))

    # Apply fleet mapping based on service type filter
    if filters.get("services"):
        mapped_vehicles = []
        for s in filters["services"]:
            if "ride" in s.lower() or "send" in s.lower() or "food" in s.lower():
                mapped_vehicles.append("motor")
            if "car" in s.lower() or "bluebird" in s.lower():
                mapped_vehicles.append("mobil")
        
        if mapped_vehicles:
            df_summary = df_summary[df_summary["vehicle_type"].str.lower().isin(mapped_vehicles)]
            df_rating = df_rating[df_rating["vehicle_type"].str.lower().isin(mapped_vehicles)]
            df_top = df_top[df_top["vehicle_type"].str.lower().isin(mapped_vehicles)]

    df_top = df_top.head(20)

    # Show warning if selected filters return empty data
    if df_summary.empty:
        st.warning("No fleet data found matching the selected Global Filters combination. Please adjust your sidebar settings.")
        return

    # Fleet Status Overview
    section_header("Fleet Status & Metrics Overview")
    aktif_df  = df_summary[df_summary["driver_status"].str.lower() == "aktif"]
    total_rev = df_summary["total_revenue_generated"].sum()

    col1, col2, col3, col4 = st.columns(4)
    col1.metric("Active Drivers Count", format_number(aktif_df['driver_count'].sum()))
    col2.metric("Total Driver Gross Revenue", format_rupiah(total_rev), help=f"Full Value: {format_rupiah(total_rev)}")
    col3.metric("Fleet Average Customer Rating", f"{df_summary['avg_rating'].mean():.2f} / 5.0")
    col4.metric("Average Trip Distance", f"{df_summary['avg_distance_km'].mean():.1f} km")

    # Performance statistics by vehicle
    section_header("Performance Statistics by Vehicle Type & Status")
    col1, col2 = st.columns(2)

    with col1:
        fig = bar_grouped(
            df_summary, x="vehicle_type",
            y="total_revenue_generated", color="driver_status",
            title="Gross Revenue Generated by Fleet Category",
        )
        st.plotly_chart(fig, width="stretch", theme=None)

    with col2:
        fig = bar_grouped(
            df_summary, x="vehicle_type",
            y="avg_rating", color="driver_status",
            title="Average Customer Satisfaction Rating",
        )
        fig.update_layout(yaxis=dict(range=[3, 5.1]))
        st.plotly_chart(fig, width="stretch", theme=None)

    # Fleet quality metrics
    section_header("Fleet Quality Assurance Metrics")
    col1, col2 = st.columns([1, 2])

    with col1:
        avg_cancel = df_summary["cancellation_rate_pct"].mean()
        fig = gauge_kpi(
            value=round(avg_cancel, 2),
            title="Average Driver Cancellation Rate",
            threshold=15.0, unit="%",
        )
        st.plotly_chart(fig, width="stretch", theme=None)

    with col2:
        fig = bar_grouped(
            df_rating, x="rating_bucket", y="driver_count", color="vehicle_type",
            title="Driver Distribution across Rating Buckets",
        )
        st.plotly_chart(fig, width="stretch", theme=None)

    # Top individual driver performers
    section_header("Top 20 Active High-Earner Drivers")
    display_top = df_top.copy()
    display_top["total_revenue"] = display_top["total_revenue"].apply(format_rupiah)
    display_top["rating"] = display_top["rating"].apply(lambda x: f"{x} / 5.0")
    df_html = display_top.rename(columns={
        "driver_id": "Driver ID", "vehicle_type": "Vehicle Type",
        "driver_status": "Status", "rating": "Rating",
        "total_orders": "Total Orders", "completed": "Completed Orders",
        "total_revenue": "Total Revenue", "avg_distance_km": "Avg Distance (km)",
    }).to_html(classes="custom-table", index=False, escape=False)
    
    with st.expander("View Top 20 Active High-Earner Drivers Table", expanded=False):
        st.markdown(df_html, unsafe_allow_html=True)

    # Automated Insights Generation
    best_vehicle = df_summary.loc[df_summary["total_revenue_generated"].idxmax()]
    top_driver   = df_top.iloc[0]
    elite_count  = df_rating[df_rating["rating_bucket"].str.contains("Elite|4.8", case=False, na=True)]["driver_count"].sum()

    insight_box("Driver Performance Insights", [
        f"The fleet segment consisting of <b>{best_vehicle['vehicle_type'].title()}</b> vehicles with an active status of "
        f"<b>{best_vehicle['driver_status']}</b> generated the highest gross revenue of <b>{format_rupiah(best_vehicle['total_revenue_generated'])}</b>.",
        f"The top-performing driver (ID: <b>{top_driver['driver_id']}</b>) successfully completed <b>{format_number(top_driver['completed'])} orders</b>, "
        f"securing an individual revenue of <b>{format_rupiah(top_driver['total_revenue'])}</b>.",
        f"A total of <b>{format_number(elite_count)} active drivers</b> qualify for the 'Elite Bucket' (Rating 4.8–5.0). "
        f"Offering loyalty perks like order priority is highly recommended to lower driver churn.",
        f"The average fleet cancellation rate is at a stable <b>{avg_cancel:.1f}%</b>. "
        f"Drivers exceeding the 15% corporate threshold should receive automated quality warnings.",
    ])
