[theme]
base            = "dark"
backgroundColor         = "#080D14"
secondaryBackgroundColor = "#0F1620"
primaryColor    = "#00AA5B"
textColor       = "#E2E8F0"

[server]
headless        = true
runOnSave       = true

[client]
showErrorDetails = true
